<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/" lang="{% for language in languages %}{% if language.active %}{{ language.lang }}{% endif %}{% endfor %}">
<head>

    <link rel="preconnect" href="{{ store_resource_hints }}" />
    <link rel="dns-prefetch" href="{{ store_resource_hints }}" />

    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{{ page_title }}</title>
    <meta name="description" content="{{ page_description }}">

   {% if settings.fb_admins %}
        {# FB user ids that can moderate the FB comments generated by the plugin. To find your ids go to: http://findmyfbid.com/ #}
        <meta property="fb:admins" content="{{ settings.fb_admins }}">
    {% endif %}
    {% if store_fb_app_id %}
        <meta property="fb:app_id" content="{{ store_fb_app_id }}">
    {% elseif not store.has_custom_domain %}
        <meta property="fb:app_id" content="{{ fb_app.id }}">
    {% endif %}

    {# Preload of first image of Slider and first Category Banners to improve LCP #}
    {% if template == 'home'%}
        {% snipplet 'preload-images.tpl' %}
    {% endif %}

    {# OG tags to control how the page appears when shared on social networks. See http://ogp.me/ #}
    {% snipplet "metas/general-og.tpl" %}

    {# Twitter tags to control how the page appears when shared on Twitter. See https://dev.twitter.com/cards/markup #}
    {% if template == 'product' %}
        {# Twitter #}
        {% snipplet "metas/twitter-product.tpl" %}
        {# Facebook #}
        {% snipplet "metas/facebook-product-og.tpl" %}
    {% elseif template == 'category' %}
        {# Facebook #}
        {% snipplet "metas/facebook-category-og.tpl" %}
    {% endif %}

    {# load fonts #}

    {# Critical CSS needed to show first elements of store while CSS async is loading #}

    <style>
        {# Font families #}

        {% if params.preview %}

            {# If page is loaded from customization page on the admin, load all fonts #}

            @import url('https://fonts.googleapis.com/css?family=Lato:700,400italic,700italic|Slabo+27px|Oswald:400,300,700|Istok+Web:400,700,400italic,700italic|Arvo:400,700,400italic,700italic|Montserrat:400,700|Open+Sans+Condensed:300,300italic,700|Open+Sans:400,300,700|Lora:400,700|Roboto+Condensed:400italic,700italic,300,400,700|Droid+Sans:400,700&display=swap');

        {% else %}

            {# If page is NOT loaded from customization only load saved fonts #}

            {# Get only the saved fonts on settings #}

            @import url('{{ [settings.font_headings, settings.font_rest, settings.font_logo] | google_fonts_url('300, 400, 700') | raw }}');

        {% endif %}

        {% snipplet 'css/critical-css.tpl' %}
    </style>

    {# ============================================
       STICKY FOOTER - KOSTÜME
       Footer siempre pegado al fondo de la pantalla
       ============================================ #}
    <style>
        .js-page-wrapper {
            display: flex !important;
            flex-direction: column !important;
            min-height: 100vh !important;
        }
        .js-main-content,
        .main-content {
            flex: 1 1 auto !important;
        }
        /* Animación de apertura del menú - easy ease */
        .new-modal {
            transition: all 0.4s cubic-bezier(0.65, 0, 0.35, 1) !important;
        }
    </style>

    {# ============================================
       INVERSIÓN DE TEMA - KOSTÜME
       Activa tema claro: fondos blancos, textos negros
       Las imágenes, fotos y logos NO se invierten
       ============================================ #}
    <style>
        /* 1. INVERTIR TODO EL SITIO */
        /* Aplicado en body (no html) para no romper 100vh en Safari */
        body {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* Sombra del navbar se invierte a un gris/blanco distinto → línea bajo el menú */
        .navbar,
        .nav-main,
        .js-main-navbar {
            box-shadow: none !important;
        }

        /* filter:invert en body crea containing block: position:fixed no pega al
           viewport. Forzar flujo normal evita huecos/solapes del sticky roto. */
        .navbar.head-fix,
        .mobile-nav.head-fix,
        .js-main-navbar.head-fix {
            position: relative !important;
            top: auto !important;
            width: 100% !important;
        }

        /* Modales escapados a <html> (JS) → fixed al viewport, no al scroll del body.
           Re-invert solo el panel para mantener colores del tema. Backdrop oscuro sin invert. */
        html > .js-modal-viewport-fixed.modal,
        html > .shipping-pickup-modal.modal,
        html > .js-modal-shipping-suboptions.modal {
            position: fixed !important;
            top: 0 !important;
            right: 0 !important;
            bottom: 0 !important;
            left: 0 !important;
            width: 100% !important;
            max-width: none !important;
            height: 100% !important;
            max-height: none !important;
            margin: 0 !important;
            padding: 15px !important;
            overflow: hidden !important;
            background: transparent !important;
            border: 0 !important;
            border-radius: 0 !important;
            box-shadow: none !important;
            -webkit-transform: none !important;
            -ms-transform: none !important;
            transform: none !important;
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
            z-index: 10000 !important;
        }
        html > .js-modal-viewport-fixed.modal.in,
        html > .js-modal-viewport-fixed.modal.fade.in,
        html > .shipping-pickup-modal.modal.in,
        html > .shipping-pickup-modal.modal.fade.in,
        html > .js-modal-shipping-suboptions.modal.in,
        html > .js-modal-shipping-suboptions.modal.fade.in {
            display: -webkit-box !important;
            display: -ms-flexbox !important;
            display: flex !important;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            justify-content: center;
            opacity: 1 !important;
        }
        html > .modal-backdrop.js-modal-viewport-backdrop,
        html > .modal-backdrop.modal-backdrop-zindex-top {
            position: fixed !important;
            top: 0 !important;
            right: 0 !important;
            bottom: 0 !important;
            left: 0 !important;
            width: 100% !important;
            height: 100% !important;
            margin: 0 !important;
            background-color: #000 !important;
            opacity: 0.45 !important;
            -webkit-filter: none !important;
            filter: none !important;
            z-index: 9999 !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-dialog,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-dialog,
        html > .shipping-pickup-modal .shipping-pickup-modal-content,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-content {
            max-height: 80vh !important;
            width: 100% !important;
            max-width: 420px !important;
            margin: 0 auto !important;
            box-sizing: border-box !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-content,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-content {
            background: #070707 !important;
            color: #fff !important;
            border: 1px solid #2a2a2a !important;
            overflow: hidden !important;
            max-height: 70vh !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-header,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-header {
            position: relative !important;
            margin: 0 !important;
            padding: 15px 48px 15px 15px !important;
            border-bottom: 1px solid #2a2a2a !important;
            box-sizing: border-box !important;
            background: #070707 !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-header:before,
        html > .shipping-pickup-modal .shipping-pickup-modal-header:after,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-header:before,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-header:after {
            display: none !important;
            content: none !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-title,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-title {
            margin: 0 !important;
            padding: 0 !important;
            font-size: 12px !important;
            font-weight: 700 !important;
            letter-spacing: 0.1em !important;
            text-transform: uppercase !important;
            text-align: left !important;
            color: #fff !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-close,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-close {
            position: absolute !important;
            top: 12px !important;
            right: 12px !important;
            width: 32px !important;
            height: 32px !important;
            margin: 0 !important;
            padding: 0 !important;
            display: -webkit-inline-box !important;
            display: -ms-inline-flexbox !important;
            display: inline-flex !important;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            justify-content: center;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-close svg,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-close svg {
            width: 14px !important;
            height: 14px !important;
            fill: #fff !important;
            color: #fff !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-item,
        html > .js-modal-shipping-suboptions .shipping-pickup-item {
            padding: 12px 15px !important;
            margin: 0 !important;
            background: #070707 !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-body,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-body {
            background: #070707 !important;
        }
        html > .shipping-pickup-modal .shipping-pickup-modal-footer,
        html > .js-modal-shipping-suboptions .shipping-pickup-modal-footer {
            padding: 12px 15px 14px !important;
            background: #0d0d0d !important;
        }
        html > .js-modal-viewport-fixed.modal .modal-header:before,
        html > .js-modal-viewport-fixed.modal .modal-header:after {
            display: none !important;
            content: none !important;
        }
        html > .js-modal-viewport-fixed.modal .modal-header {
            position: relative !important;
            padding: 15px 48px 15px 15px !important;
            box-sizing: border-box !important;
        }
        html > .js-modal-viewport-fixed.modal .modal-header h3 {
            margin: 0 !important;
            font-size: 12px !important;
            font-weight: 700 !important;
            letter-spacing: 0.1em !important;
            text-transform: uppercase !important;
            text-align: left !important;
        }
        html > .js-modal-viewport-fixed.modal .modal-header .btn-floating {
            position: absolute !important;
            top: 10px !important;
            right: 10px !important;
            width: 32px !important;
            height: 32px !important;
            margin: 0 !important;
            float: none !important;
        }
        html > .js-modal-viewport-fixed.modal .modal-body {
            padding: 15px !important;
        }
        html > .js-modal-viewport-fixed.modal .modal-footer {
            padding: 12px 15px 14px !important;
        }
        @media (max-width: 767px) {
            html > .js-modal-viewport-fixed.modal,
            html > .shipping-pickup-modal.modal,
            html > .js-modal-shipping-suboptions.modal {
                padding: 15px !important;
            }
        }

        /* Panel de variantes mobile escapado a <html> (mismo bug de filter/fixed). */
        html > .js-mobile-vars-panel.js-mobile-vars-viewport-fixed {
            position: fixed !important;
            top: 0 !important;
            right: 0 !important;
            bottom: 0 !important;
            left: 0 !important;
            width: 100% !important;
            max-width: none !important;
            height: 100% !important;
            max-height: 100vh !important;
            margin: 0 !important;
            overflow: hidden !important;
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
            z-index: 10000 !important;
        }
        html > .js-mobile-vars-panel.js-mobile-vars-viewport-fixed.modal-xs-right-in {
            -webkit-transform: translate3d(0, 0, 0) !important;
            -ms-transform: translate3d(0, 0, 0) !important;
            transform: translate3d(0, 0, 0) !important;
        }
        html > .js-mobile-vars-panel.js-mobile-vars-viewport-fixed.modal-xs-right-out {
            -webkit-transform: translate3d(100%, 0, 0) !important;
            -ms-transform: translate3d(100%, 0, 0) !important;
            transform: translate3d(100%, 0, 0) !important;
        }
        html > .js-mobile-vars-panel.js-mobile-vars-viewport-fixed .modal-xs-dialog {
            height: 100% !important;
            max-height: 100vh !important;
            overflow: auto !important;
            -webkit-overflow-scrolling: touch;
        }

        /* Ajax cart + medios de pago: mismo escape a <html> (VER CARRITO en PDP, etc.) */
        html > .js-ajax-cart-panel.js-ajax-cart-viewport-fixed,
        html > #installments-modal.js-installments-viewport-fixed {
            position: fixed !important;
            top: 0 !important;
            right: 0 !important;
            bottom: 0 !important;
            left: 0 !important;
            width: 100% !important;
            max-width: none !important;
            height: 100% !important;
            max-height: 100vh !important;
            margin: 0 !important;
            padding: 0 !important;
            overflow: auto !important;
            -webkit-overflow-scrolling: touch;
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
            z-index: 10000 !important;
            background: #070707 !important;
            color: #fff !important;
        }
        html > .js-ajax-cart-panel.js-ajax-cart-viewport-fixed.modal-xs-right-in,
        html > #installments-modal.js-installments-viewport-fixed.modal-xs-right-in,
        html > #installments-modal.js-installments-viewport-fixed.in {
            -webkit-transform: translate3d(0, 0, 0) !important;
            -ms-transform: translate3d(0, 0, 0) !important;
            transform: translate3d(0, 0, 0) !important;
            display: block !important;
            opacity: 1 !important;
        }
        html > .js-ajax-cart-panel.js-ajax-cart-viewport-fixed.modal-xs-right-out,
        html > #installments-modal.js-installments-viewport-fixed.modal-xs-right-out {
            -webkit-transform: translate3d(100%, 0, 0) !important;
            -ms-transform: translate3d(100%, 0, 0) !important;
            transform: translate3d(100%, 0, 0) !important;
        }
        html > #installments-modal.js-installments-viewport-fixed .modal-dialog,
        html > #installments-modal.js-installments-viewport-fixed .modal-xs-dialog,
        html > #installments-modal.js-installments-viewport-fixed .modal-content {
            width: 100% !important;
            max-width: none !important;
            height: 100% !important;
            max-height: 100vh !important;
            margin: 0 !important;
            background: #070707 !important;
            color: #fff !important;
            border: 0 !important;
            border-radius: 0 !important;
            box-shadow: none !important;
        }

        /* Breadcrumbs: fondo del tema (#070707) → blanco con invert.
           Sin margins (crean huecos negros fuera del filter).
           Producto: gutter 15px en el propio bar (full-bleed).
           Categoría: el gutter lo da el title-container; sin padding extra. */
        .breadcrumb,
        .product-breadcrumb {
            background: #070707 !important;
            background-color: #070707 !important;
            border-radius: 0 !important;
            margin: 0 !important;
            box-sizing: border-box !important;
        }
        .product-breadcrumb.breadcrumb {
            width: 100% !important;
            max-width: 100% !important;
            padding: 10px 15px !important;
        }
        @media (max-width: 767px) {
            .product-breadcrumb.breadcrumb {
                padding-top: 16px !important;
            }
        }
        .title-container .breadcrumb,
        .breadcrumb-product .breadcrumb {
            width: auto !important;
            max-width: none !important;
            padding: 0 !important;
            background: transparent !important;
            background-color: transparent !important;
        }
        .product-breadcrumb,
        .product-breadcrumb .breadcrumb-crumb,
        .product-breadcrumb .breadcrumb-crumb.active,
        .product-breadcrumb .breadcrumb-divider,
        .product-breadcrumb a {
            color: #ffffff !important;
            text-shadow: none !important;
        }

        /* Productos relacionados / cards de grilla: mismos fondos del tema.
           Fondos #000/#fff o white de Bootstrap quedan negros al invertir. */
        #related-products,
        .item-image-container,
        .item-info-container,
        .product-single-image {
            background: #070707 !important;
            background-color: #070707 !important;
        }
        #related-products,
        #related-products h5,
        #related-products .item-name,
        #related-products .item-price {
            color: #ffffff !important;
        }

        /* Fix Safari: asegurar que menú sea clickeable */
        .js-modal-open,
        .js-modal-close,
        .mobile-nav-first-row-icon,
        #nav-hamburger {
            pointer-events: auto !important;
            -webkit-transform: translateZ(0) !important;
            transform: translateZ(0) !important;
        }

        /* CENTRAR TODO el menú hamburger (items principales Y subitems) */
        .hamburger-panel .list-items,
        .hamburger-panel .list-items li,
        .hamburger-panel .list-items .hamburger-panel-link,
        .hamburger-panel-link,
        .list-items .hamburger-panel-link,
        .item-with-subitems {
            text-align: center !important;
        }

        .hamburger-panel .list-items .list-subitems,
        .hamburger-panel .list-items .list-subitems li,
        .list-subitems,
        .hamburger-panel-item {
            text-align: center !important;
        }

        .js-hamburger-panel-toggle-accordion {
            text-align: center !important;
        }

        .js-pages-accordion.hamburger-panel-accordion,
        .hamburger-panel-accordion {
            text-align: center !important;
        }

        .hamburger-panel-accordion li {
            text-align: center !important;
        }

        .hamburger-panel .js-hamburger-panel-toggle-accordion .hamburger-panel-link {
            padding-left: 20px !important;
            padding-right: 20px !important;
        }

        .hamburger-panel .list-subitems {
            padding-left: 0 !important;
            margin-left: 0 !important;
        }

        /* 2. RE-INVERTIR: Todas las imágenes (genérico) */
        img,
        picture,
        video,
        img.lazyload,
        img.lazyloading,
        img.lazyloaded {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
            will-change: filter !important;
            -webkit-backface-visibility: hidden !important;
            backface-visibility: hidden !important;
        }

        /* Fix específico Safari: imágenes de producto cortadas */
        .item-image,
        .js-item-image {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
            width: 100% !important;
            max-width: 100% !important;
            height: auto !important;
            will-change: filter !important;
            -webkit-backface-visibility: hidden !important;
            backface-visibility: hidden !important;
        }

        /* 3. RE-INVERTIR: Imágenes de producto en grid de categoría (específico) */
        .category-products-grid img,
        .category-products-grid .item-image,
        .category-products-grid .js-item-image,
        .category-products-grid .item-image-container img,
        .js-masonry-grid img,
        .js-masonry-grid .item-image,
        .js-masonry-grid .js-item-image,
        .js-masonry-item img,
        .js-masonry-item .item-image,
        .js-masonry-item .js-item-image {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 4. RE-INVERTIR: Productos relacionados */
        .horizontal-products-container img,
        .horizontal-products-container .item-image,
        .horizontal-products-container .js-item-image,
        #related-products img {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 5. RE-INVERTIR: Productos destacados en home */
        .primary-products-grid img,
        .products-grid img {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 6. RE-INVERTIR: Imágenes en detalle de producto */
        .product-image img,
        .js-product-slide-img,
        .product-slider img,
        .product-detail img {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 7. RE-INVERTIR: Logo y SVG de marca */
        #logo,
        #logo img,
        #logo svg,
        .logo-img-container,
        .logo-img-container svg,
        .logo-img {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
            -webkit-transform: translateZ(0) !important;
            transform: translateZ(0) !important;
            isolation: isolate !important;
        }

        /* 8. RE-INVERTIR: Banners y sliders */
        .banner-image,
        .banner img,
        .swiper-slide img,
        .textbanner-image-background,
        .category-banner img,
        .home-slider img {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 9. RE-INVERTIR: Imágenes de pagos, envíos, sellos */
        .card-img,
        .footer-payship-img,
        .card-img-square,
        .payment-new-logo,
        img[data-src*="payment"],
        img[data-src*="shipping"],
        .payment-method-logo,
        .shipping-method-logo {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 10. RE-INVERTIR: Modales, quickshop, cart */
        .modal img,
        .quick-shop img,
        .quickshop-img,
        .js-quickshop-img,
        .ajax-cart-container img,
        .ajax-cart-item-image-col img,
        .cart-item img {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 11. RE-INVERTIR: Placeholders y preloaders */
        .embed-responsive img,
        .product-thumb img,
        .placeholder-icon {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 12. RE-INVERTIR: Zoom de producto (CloudZoom) */
        .cloud-zoom-big,
        #cloud-zoom-big,
        .cloud-zoom-lens,
        .zoomWindow,
        .zoomContainer,
        .zoomWindowContainer,
        .zoomLens {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        /* 13. RE-INVERTIR: UI de terceros de Tienda Nube (wallet / login modal).
           El invert del body los deja con contraste roto (fondo negro, marca amarilla).
           Re-invertir el contenedor restaura colores originales; imgs internas
           no deben llevar el invert genérico o quedarían invertidas de nuevo. */
        [class*="wallet-lib-auth"],
        [class*="wallet-lib-storefront"],
        [data-rsbs-root],
        [data-rsbs-overlay],
        [data-rsbs-backdrop],
        #walletAuthProxyIframe,
        iframe[src*="nuvempay"],
        iframe[src*="services-wallet"] {
            -webkit-filter: invert(1) !important;
            filter: invert(1) !important;
        }

        [class*="wallet-lib-auth"] img,
        [class*="wallet-lib-storefront"] img,
        [data-rsbs-root] img,
        [data-rsbs-overlay] img {
            -webkit-filter: none !important;
            filter: none !important;
        }
    </style>

    {# Load async styling not mandatory for first meaningfull paint #}

    {% snipplet 'js/load-css-async.tpl' %}

    {# Colors and fonts used from settings.txt and defined on theme customization #}

    {{ 'css/custom-styles.scss.tpl' | static_url | css_tag }}

    {# Merchant's custom CSS #}

    <style>
        {{ settings.css_code | raw }}
    </style>

    {# Defines if async JS will be used by using script_tag(true) #}

    {% set async_js = true %}

    {# Defines the usage of jquery loaded below, if nojquery = true is deleted it will fallback to jquery 1.5 #}

    {% set nojquery = true %}

    {# Jquery async by adding script_tag(true) #}

    {{ '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' | script_tag(true) }}

    {# Loads private Tiendanube JS #}

    {% head_content %}

    {# Structured data to provide information for Google about the page content #}

    {% include 'snipplets/structured_data/webpage-structured-data.tpl' %}

</head>
<body class="{% if customer %}customer-logged-in{% endif %} template-{{ template | replace('.', '-') }}">

{# Social JS for Twitter home widgets and Facebook comments on product page #}
{% if template == 'home' %}

    {# Twitter profile feed JS #}
    {% if settings.twitter_widget %}
        {{ tw_js }}
    {% endif %}
{% endif %}
{% if template == 'product' %}
    {# Facebook comment box JS #}
    {% if settings.show_product_fb_comment_box %}
        {{ fb_js }}
    {% endif %}
    {# Pinterest share button JS #}
    {{ pin_js }}
{% endif %}

{% if template == 'account.login' or template == 'account.register' %}
    {{ fb_js }}
{% endif %}

{# Only remove this if you want to take away the theme onboarding advices #}
{% set show_help = not has_products %}

    {# Includes a fixed bar that let logged in merchants go back to their admin panel #}
    {{back_to_admin}}

    {# Hamburger panel #}
    <nav id="nav-hamburger" class="js-modal new-modal modal-left hamburger-panel" style="display: none;">
        {% snipplet "navigation/navigation-hamburger-panel.tpl" %}
    </nav>

    {# Site Overlay #}
    <div class="js-modal-overlay site-overlay visible-phone"></div>

    {#  **** Store Main Container ****  #}
    <div class="js-page-wrapper">
        {# Marquee #}
        {% if template == 'home' %}
            {# {% include 'snipplets/marquee.tpl' %} #}
        {% endif %}
        {% snipplet "navigation/header-nav.tpl" %}
        {# template_content renders the template file #}
        {% if template == 'product' %}
		    {% snipplet "navigation/breadcrumbs.tpl" %}
	    {% endif %}
        <div style="background-color: #070707; padding-top: 0px;" class="js-main-content main-content {% if template == 'product' %}no-margin{% endif %} {% if store.has_accounts or languages | length > 1 %} with-top-bar{% endif %} {% if status_page_url %}with-notification-bar{% endif %}">
            {% template_content %}

            {# Quickshop modal #}
            {% snipplet "product-grid/quick-shop.tpl" %}
        </div>
        {% snipplet "footer.tpl" %}
    </div>

        {# Our themes do not support IE versions lower than IE8 #}
        <!--[if lt IE 8]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->


{# Javascript used in the store #}

<script type="text/javascript">

    {# Libraries that do NOT depend on other libraries, e.g: Jquery #}

    {% include "static/js/external-no-dependencies.js.tpl" %}

    {# LS.ready.then function waits to Jquery and private Tiendanube JS to be loaded before executing what´s inside #}

    LS.ready.then(function(){

        {# Libraries that requires Jquery to work #}

        {% snipplet "js/external.js.tpl"  %}

        {# Specific store JS functions: product variants, cart, shipping, etc #}

        {% snipplet "js/store.js.tpl"  %}
    });
</script>

{# Google reCAPTCHA on register page #}
{% if template == 'account.register' %}
    {% if not store.hasContactFormsRecaptcha() %}
        {{ '//www.google.com/recaptcha/api.js' | script_tag(true) }}
    {% endif %}
    <script type="text/javascript">
        var recaptchaCallback = function() {
            $('.js-recaptcha-button').prop('disabled', false);
        };
    </script>
{% endif %}

{# Google Survey JS #}
{% if store.google_merchant_id %}
    {% snipplet "js/google-survey.js.tpl"  %}
{% endif %}

{# Private Sale Password Protection - Al final del body #}
{# DESACTIVADO TEMPORALMENTE #}
{# {% snipplet "vip-protection.tpl" %} #}

</body>
</html>
