<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/" lang="{% for language in languages %}{% if language.active %}{{ language.lang }}{% endif %}{% endfor %}">
<head>

    <link rel="preconnect" href="{{ store_resource_hints }}" />
    <link rel="dns-prefetch" href="{{ store_resource_hints }}" />

    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{{ page_title }}</title>
    <meta name="description" content="{{ page_description }}">

   {% if settings.fb_admins %}
        {# FB user ids that can moderate the FB comments generated by the plugin. To find your ids go to: http://findmyfbid.com/ #}
        <meta property="fb:admins" content="{{ settings.fb_admins }}">
    {% endif %}
    {% if store_fb_app_id %}
        <meta property="fb:app_id" content="{{ store_fb_app_id }}">
    {% elseif not store.has_custom_domain %}
        <meta property="fb:app_id" content="{{ fb_app.id }}">
    {% endif %}

    {# Preload of first image of Slider and first Category Banners to improve LCP #}
    {% if template == 'home'%}
        {% snipplet 'preload-images.tpl' %}
    {% endif %}

    {# OG tags to control how the page appears when shared on social networks. See http://ogp.me/ #}
    {% snipplet "metas/general-og.tpl" %}

    {# Twitter tags to control how the page appears when shared on Twitter. See https://dev.twitter.com/cards/markup #}
    {% if template == 'product' %}
        {# Twitter #}
        {% snipplet "metas/twitter-product.tpl" %}
        {# Facebook #}
        {% snipplet "metas/facebook-product-og.tpl" %}
    {% elseif template == 'category' %}
        {# Facebook #}
        {% snipplet "metas/facebook-category-og.tpl" %}
    {% endif %}

    {# load fonts #}

    {# Critical CSS needed to show first elements of store while CSS async is loading #}

    <style>
        {# Font families #}

        {% if params.preview %}

            {# If page is loaded from customization page on the admin, load all fonts #}

            @import url('https://fonts.googleapis.com/css?family=Lato:700,400italic,700italic|Slabo+27px|Oswald:400,300,700|Istok+Web:400,700,400italic,700italic|Arvo:400,700,400italic,700italic|Montserrat:400,700|Open+Sans+Condensed:300,300italic,700|Open+Sans:400,300,700|Lora:400,700|Roboto+Condensed:400italic,700italic,300,400,700|Droid+Sans:400,700&display=swap');

        {% else %}

            {# If page is NOT loaded from customization only load saved fonts #}

            {# Get only the saved fonts on settings #}

            @import url('{{ [settings.font_headings, settings.font_rest, settings.font_logo] | google_fonts_url('300, 400, 700') | raw }}');

        {% endif %}

        {% snipplet 'css/critical-css.tpl' %}
    </style>


    {# Load async styling not mandatory for first meaningfull paint #}

    {% snipplet 'js/load-css-async.tpl' %}

    {# Colors and fonts used from settings.txt and defined on theme customization #}

    {{ 'css/custom-styles.scss.tpl' | static_url | css_tag }}

    {# Merchant's custom CSS #}

    <style>
        {{ settings.css_code | raw }}
    </style>

    {# Defines if async JS will be used by using script_tag(true) #}

    {% set async_js = true %}

    {# Defines the usage of jquery loaded below, if nojquery = true is deleted it will fallback to jquery 1.5 #}

    {% set nojquery = true %}

    {# Jquery async by adding script_tag(true) #}

    {{ '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' | script_tag(true) }}

    {# Loads private Tiendanube JS #}

    {% head_content %}

    {# Structured data to provide information for Google about the page content #}

    {% include 'snipplets/structured_data/webpage-structured-data.tpl' %}


</head>
<body class="{% if customer %}customer-logged-in{% endif %} template-{{ template | replace('.', '-') }}">

{# Social JS for Twitter home widgets and Facebook comments on product page #}
{% if template == 'home' %}

    {# Twitter profile feed JS #}
    {% if settings.twitter_widget %}
        {{ tw_js }}
    {% endif %}
{% endif %}
{% if template == 'product' %}
    {# Facebook comment box JS #}
    {% if settings.show_product_fb_comment_box %}
        {{ fb_js }}
    {% endif %}
    {# Pinterest share button JS #}
    {{ pin_js }}
{% endif %}

{% if template == 'account.login' or template == 'account.register' %}
    {{ fb_js }}
{% endif %}

{# Only remove this if you want to take away the theme onboarding advices #}
{% set show_help = not has_products %}

    {# Includes a fixed bar that let logged in merchants go back to their admin panel #}
    {{back_to_admin}}

    {# Hamburger panel #}
    <nav id="nav-hamburger" class="js-modal new-modal modal-left hamburger-panel" style="display: none;">
        {% snipplet "navigation/navigation-hamburger-panel.tpl" %}
    </nav>

    {# Site Overlay #}
    <div class="js-modal-overlay site-overlay visible-phone"></div>

    {#  **** Store Main Container ****  #}
        {# Marquee #}
        {% if template == 'home' %}
            {# {% include 'snipplets/marquee.tpl' %} #}
        {% endif %}
        {% snipplet "navigation/header-nav.tpl" %}
        {# template_content renders the template file #}
        {% if template == 'product' %}
		    {% snipplet "navigation/breadcrumbs.tpl" %}
	    {% endif %}
        <div style="background-color: #070707; padding-top: 0px;" class="js-main-content  main-content {% if template == 'product' %}no-margin{% endif %} {% if store.has_accounts or languages | length > 1 %} with-top-bar{% endif %} {% if status_page_url %}with-notification-bar{% endif %}">
            {% template_content %}

            {# Quickshop modal #}
            {% snipplet "product-grid/quick-shop.tpl" %}
        </div>
        {% snipplet "footer.tpl" %}

        {# Our themes do not support IE versions lower than IE8 #}
        <!--[if lt IE 8]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->


{# Javascript used in the store #}

<script type="text/javascript">

    {# Libraries that do NOT depend on other libraries, e.g: Jquery #}

    {% include "static/js/external-no-dependencies.js.tpl" %}

    {# LS.ready.then function waits to Jquery and private Tiendanube JS to be loaded before executing what´s inside #}

    LS.ready.then(function(){

        {# Libraries that requires Jquery to work #}

        {% snipplet "js/external.js.tpl"  %}

        {# Specific store JS functions: product variants, cart, shipping, etc #}

        {% snipplet "js/store.js.tpl"  %}
    });
</script>

{# Google reCAPTCHA on register page #}
{% if template == 'account.register' %}
    {% if not store.hasContactFormsRecaptcha() %}
        {{ '//www.google.com/recaptcha/api.js' | script_tag(true) }}
    {% endif %}
    <script type="text/javascript">
        var recaptchaCallback = function() {
            $('.js-recaptcha-button').prop('disabled', false);
        };
    </script>
{% endif %}

{# Google Survey JS #}
{% if store.google_merchant_id %}
    {% snipplet "js/google-survey.js.tpl"  %}
{% endif %}

</body>
</html>
