<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 9 ]><html class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html class="no-js"><!--<![endif]-->
<head>
     <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1">

    <title>{{ page_title }}</title>
    <meta name="description" content="{{ page_description }}">

   {% if settings.fb_admins %}
        {# FB user ids that can moderate the FB comments generated by the plugin. To find your ids go to: http://findmyfbid.com/ #}
        <meta property="fb:admins" content="{{ settings.fb_admins }}">
    {% endif %}
    {% if store_fb_app_id %}
        <meta property="fb:app_id" content="{{ store_fb_app_id }}">
    {% elseif not store.has_custom_domain %}
        <meta property="fb:app_id" content="{{ fb_app.id }}">
    {% endif %}

    {# OG tags to control how the page appears when shared on social networks. See http://ogp.me/ #}
    {% snipplet "metas/general-og.tpl" %}

    {# Critical CSS to improve the percieved performance on first load #}
    <style>
        {% snipplet 'css/critical-css.tpl' %}
    </style>

    {# load fonts #}

    {% if params.preview %}

        {# If page is loaded from customization page on the admin, load all fonts #}

        {{ '//fonts.googleapis.com/css?family=Lato:700,400italic,700italic|Slabo+27px|Oswald:400,300,700|Istok+Web:400,700,400italic,700italic|Arvo:400,700,400italic,700italic|Montserrat:400,700|Open+Sans+Condensed:300,300italic,700|Open+Sans:400,300,700|Lora:400,700|Roboto+Condensed:400italic,700italic,300,400,700|Droid+Sans:400,700&display=swap' | css_tag }}

    {% else %}

        {# If page is NOT loaded from customization only load saved fonts #}

        {# Get only the saved fonts on settings #}

        {{ [settings.font_headings, 
        settings.font_rest, 
        settings.font_logo] | google_fonts_url('300, 400, 700') | css_tag }}

    {% endif %}

    {# Aynsc CSS for the non-critical stylesheets #}
    {% snipplet 'js/load-css-async.tpl' %}

    {# load fonts #}

    {% if params.preview %}

        {# If page is loaded from customization page on the admin, load all fonts #}

        {{ '//fonts.googleapis.com/css?family=Lato:700,900,400italic,700italic|Slabo+27px|Oswald:400,300,700|Istok+Web:400,700,400italic,700italic|Arvo:400,700,400italic,700italic|Montserrat:400,700|Open+Sans+Condensed:300,300italic,700|Open+Sans:400,300,700|Lora:400,700|Roboto+Condensed:400italic,700italic,300,400,700|Droid+Sans:400,700' | css_tag }}

    {% else %}

        {# If page is NOT loaded from customization only load saved fonts #}

        {# Get only the saved fonts on settings #}

        {{ [settings.font_headings, 
        settings.font_rest, 
        settings.font_logo] | google_fonts_url | css_tag }}

    {% endif %}

    {# Aynsc CSS for the non-critical stylesheets #}
    {% snipplet 'js/load-css-async.tpl' %}

    {# Theme's CSS #}
    {{ 'css/custom-styles.scss.tpl' | static_url | css_tag }}

    {# Themes include jquery 1.5 by default. With this setting we can include our own jQuery #}
    {% set nojquery = true %}
    {{ '//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js' | script_tag }}
    {% if params.preview %}
        {{ 'js/instatheme.js' | static_url | script_tag }}
    {% endif %}
    <script>jQuery('html').removeClass('no-js').addClass('js');</script>

    {% head_content %}

    {# Structured data to provide information for Google about the page content #}
    {% include 'snipplets/structured_data/webpage-structured-data.tpl' %}

    {# Merchant's custom CSS #}
    <style>
        {{ settings.css_code | raw }}
    </style>
</head>
<body class="template-{{ template }}">
{{ social_js }}
{{back_to_admin}}
<div class="container text-center visible-when-content-ready">
    <div class="row">
        <div class="text-center m-top m-double-bottom col-xs-12">
            {% snipplet "logo.tpl" %}
        </div>
    </div>
    <div class="row m-bottom svg-icon-primary password-page-svg">
        {% include "snipplets/svg/construction.tpl" with {'animation-wiggle': true} %}
    </div>
    <h3 class="m-top m-bottom h4-xs">{{ message }}</h3>
    {% if store.facebook or store.twitter or store.pinterest or store.instagram or store.tiktok or store.youtube %}
        <ul class="list-style-none">
        {% for sn in ['instagram', 'facebook', 'youtube', 'tiktok', 'twitter', 'pinterest'] %}
            {% set sn_url = attribute(store,sn) %}
            {% if sn_url %}
                <li class="{{ sn }} m-bottom-half d-inline-block m-right-half">
                    <a target="_blank" href="{{ sn_url }}" class="btn-circle bg-{{ sn }} pull-left">
                        {% include "snipplets/svg/" ~ sn ~ ".tpl" with {fa_custom_class: "svg-main-color fa-md"} %}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}  
    </div>
</div>
<footer class="footer">
    <div class="container p-bottom-half">
        <form method="post" class="row m-top">
            <div class="form-group col-xs-12 col-xs-offset-0 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
                <input type="password" name="password" placeholder="{{ 'Contraseña de acceso' | translate }}" class="form-control m-bottom-half  {% if invalid_password == true %}input-error{% endif %}" autocomplete="off">
                <input type="submit" name="unlock" class="btn btn-primary col-xs-12 col-sm-12 col-md-12 col-lg-12" value='{{ "Desbloquear" | translate }}'>
            </div>
            {% if invalid_password == true %}
                <div class="alert alert-danger-input">{{ 'La contraseña es incorrecta.' | translate }}</div>
            {% endif %}
        </form>
        {% if store.phone or store.address or store.blog %}
            <ul class="store-contact-container list-style-none m-none text-center">
                {% if store.phone %}
                    <li>{{ store.phone }}</li>
                {% endif %}
                {% if store.address %}
                    <li>{{ store.address }}</li>
                {% endif %}
                {% if store.blog %}
                    <li class="blog"><a target="_blank" href="{{ store.blog }}">{{ store.blog }}</a></li>
                {% endif %}
                {% if store.email %}
                    <li class="email">{{ store.email | mailto }}</li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
    <div class="footer-legal p-bottom-half p-top-half">
        <div class="powered-by text-center m-double-top">
            {#
            La leyenda que aparece debajo de esta linea de código debe mantenerse
            con las mismas palabras y con su apropiado link a Tienda Nube;
            como especifican nuestros términos de uso: http://www.tiendanube.com/terminos-de-uso .
            Si quieres puedes modificar el estilo y posición de la leyenda para que se adapte a
            tu sitio. Pero debe mantenerse visible para los visitantes y con el link funcional.
            Os créditos que aparece debaixo da linha de código deverá ser mantida com as mesmas
            palavras e com seu link para Nuvem Shop; como especificam nossos Termos de Uso:
            http://www.nuvemshop.com.br/termos-de-uso. Se você quiser poderá alterar o estilo
            e a posição dos créditos para que ele se adque ao seu site. Porém você precisa
            manter visivél e com um link funcionando.
            #}
            {{ new_powered_by_link }}
        </div>
        <div class="copyright-container text-center m-bottom">
            {{ "Copyright {1} - {2}. Todos los derechos reservados." | translate( (store.business_name ? store.business_name : store.name) ~ (store.business_id ? ' - ' ~ store.business_id : ''), "now" | date('Y') ) }}
        </div>
    </div>
</footer>
</body>
</html>
